# _config.yml

# Site settings
title: Chinmay Amrutkar | Robotics Engineer
email: chinmay.amrutkar@asu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated Robotics Engineer with expertise in computer vision, image processing,
  and robotic manipulation, fueled by a passion for robotics, AI and autonomous navigation.
  Committed to developing cutting-edge algorithms for real-world challenges.
baseurl: ""
url: "https://ChinmayAmrutkar.github.io"
github_username:  ChinmayAmrutkar
linkedin_username: chinmay-amrutkar-153375209
google_scholar_id: a7ymhIIAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima theme settings
minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/ChinmayAmrutkar" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/chinmay-amrutkar-153375209" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=a7ymhIIAAAAJ&hl=en", title: "Google Scholar" }

# Markdown processor
markdown: kramdown

# ---- Add this entire block at the end of _config.yml ----

collections:
  projects:
    output: true # This ensures each project markdown file generates a page
    permalink: /projects/:path/ # Optional: Defines the URL structure, e.g., /projects/3d-object-detection/